Update pipeline

diff --git a/pipeline b/pipeline
--- a/pipeline
+++ b/pipeline
@@ -7,8 +7,6 @@ variables:
   NEXUS_REGISTRY: "fmk.nexus-ci.onefiserv.net"
   NEXUS_REPO_PATH: "apm/0006528"
   FULL_IMAGE_NAME: "$NEXUS_REGISTRY/$NEXUS_REPO_PATH/$IMAGE_NAME:$IMAGE_TAG"
-  NEXUS_REPO_USER: "svc-apim-cicd-dev"
-  NEXUS_REPO_PASS: "F_arX1Z%fIQSfZEM@aJL9RRk*"
 
 build_and_push_image:
   stage: build_and_push
@@ -19,13 +17,16 @@ build_and_push_image:
     - echo "$NEXUS_REPO_PASS" | docker login -u "$NEXUS_REPO_USER" --password-stdin "$NEXUS_REGISTRY"
 
     - echo "Checking for Dockerfile..."
-    - if [ ! -f Dockerfile ]; then echo "ERROR: Dockerfile not found in the repository root. Aborting build."; exit 1; fi
+    - |
+      if [ ! -f Dockerfile ]; then
+        echo "ERROR: Dockerfile not found in the repository root. Aborting build."
+        exit 1
+      fi
 
     - echo "Building Docker image for project $IMAGE_NAME..."
     - docker build -t "$FULL_IMAGE_NAME" .
 
     - echo "Pushing Docker image to Nexus..."
-    - echo "$FULL_IMAGE_NAME"
     - docker push "$FULL_IMAGE_NAME"
 
     - echo "Docker image successfully pushed: $FULL_IMAGE_NAME"
